### ISSUE TITLE
Linux安装报错

### ISSUE THREAD

**Issue by Absolute-2ero** [ddean2009/MoneyPrinterPlus#12]
![image](https://github.com/ddean2009/MoneyPrinterPlus/assets/85445204/a7162f56-0513-451c-8a98-3435106737ac)
请问这个报错是怎么回事呢？
将pwd改为小写之后在114行又报错：
![image](https://github.com/ddean2009/MoneyPrinterPlus/assets/85445204/1cc15661-7c91-4713-bf79-d941d978cb73)

**Comment by ddean2009** [comment]
bash setup.sh
