### ISSUE TITLE
是否可以支持最新的本地语音识别和本地文本转语音

### ISSUE THREAD

**Issue by AndrewChenVIP** [ddean2009/MoneyPrinterPlus#14]
本地语音识别开源项目：OpenAI开源的Whisper和最近阿里开源的SenseVoice。
本地文本转语音开源项目：B站大佬开源的ChatTTS和最近阿里开源的CosyVoice。
这几个项目出来结果的质量都挺高的，也有相应的API，刘悦大佬甚至还做好了整合包：https://www.bilibili.com/video/BV1wz421B7UE。
大佬是否可以考虑支持一下？

**Comment by ddean2009** [comment]
ChatTTS 已经支持了。 
Whisper 下一步支持。

**Comment by ddean2009** [comment]
fasterWhisper已经上线了。
