### ISSUE TITLE
ai生成和视频混剪都报这个错误

### ISSUE THREAD

**Issue by scj725** [ddean2009/MoneyPrinterPlus#19]
本地tts、fasterWhisper、ollama

CalledProcessError: Command '['ffmpeg', '-i', 'E:\\pyCharmProject\\MoneyPrinterPlus\\work\\1721792310586.wav', '-af', 'apad=pad_dur=2', 'E:\\pyCharmProject\\MoneyPrinterPlus\\work\\1721792310586.temp.wav']' returned non-zero exit status 4294967294.
Traceback:
File "D:\python\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 575, in _run_script
    self._session_state.on_script_will_rerun(
File "D:\python\Lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 65, in on_script_will_rerun
    self._state.on_script_will_rerun(latest_widget_states)
File "D:\python\Lib\site-packages\streamlit\runtime\state\session_state.py", line 517, in on_script_will_rerun
    self._call_callbacks()
File "D:\python\Lib\site-packages\streamlit\runtime\state\session_state.py", line 530, in _call_callbacks
    self._new_widget_state.call_callback(wid)
File "D:\python\Lib\site-packages\streamlit\runtime\state\session_state.py", line 274, in call_callback
    callback(*args, **kwargs)
File "E:\pyCharmProject\MoneyPrinterPlus\pages\01_auto_video.py", line 66, in generate_video
    main_generate_ai_video(video_generator)
File "E:\pyCharmProject\MoneyPrinterPlus\main.py", line 266, in main_generate_ai_video
    main_generate_video_dubbing()
File "E:\pyCharmProject\MoneyPrinterPlus\main.py", line 157, in main_generate_video_dubbing
    extent_audio(audio_output_file, 2)
File "E:\pyCharmProject\MoneyPrinterPlus\tools\utils.py", line 138, in extent_audio
    subprocess.run(command, capture_output=True, check=True)
File "D:\python\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,

**Comment by yuu2001** [comment]
同问

**Comment by yuu2001** [comment]
解决了，把语音识别的key配置好就可以了

**Comment by yuu2001** [comment]
> 解决了，把语音识别的key配置好就可以了



> 本地tts、fasterWhisper、ollama
> 
> CalledProcessError: Command '['ffmpeg', '-i', 'E:\pyCharmProject\MoneyPrinterPlus\work\1721792310586.wav', '-af', 'apad=pad_dur=2', 'E:\pyCharmProject\MoneyPrinterPlus\work\1721792310586.temp.wav']' returned non-zero exit status 4294967294. Traceback: File "D:\python\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 575, in _run_script self._session_state.on_script_will_rerun( File "D:\python\Lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 65, in on_script_will_rerun self._state.on_script_will_rerun(latest_widget_states) File "D:\python\Lib\site-packages\streamlit\runtime\state\session_state.py", line 517, in on_script_will_rerun self._call_callbacks() File "D:\python\Lib\site-packages\streamlit\runtime\state\session_state.py", line 530, in _call_callbacks self._new_widget_state.call_callback(wid) File "D:\python\Lib\site-packages\streamlit\runtime\state\session_state.py", line 274, in call_callback callback(*args, **kwargs) File "E:\pyCharmProject\MoneyPrinterPlus\pages\01_auto_video.py", line 66, in generate_video main_generate_ai_video(video_generator) File "E:\pyCharmProject\MoneyPrinterPlus\main.py", line 266, in main_generate_ai_video main_generate_video_dubbing() File "E:\pyCharmProject\MoneyPrinterPlus\main.py", line 157, in main_generate_video_dubbing extent_audio(audio_output_file, 2) File "E:\pyCharmProject\MoneyPrinterPlus\tools\utils.py", line 138, in extent_audio subprocess.run(command, capture_output=True, check=True) File "D:\python\Lib\subprocess.py", line 571, in run raise CalledProcessError(retcode, process.args,


解决了，把语音识别的key配置好就可以了

**Comment by yuu2001** [comment]
> 本地tts、fasterWhisper、ollama
> 
> CalledProcessError: Command '['ffmpeg', '-i', 'E:\pyCharmProject\MoneyPrinterPlus\work\1721792310586.wav', '-af', 'apad=pad_dur=2', 'E:\pyCharmProject\MoneyPrinterPlus\work\1721792310586.temp.wav']' returned non-zero exit status 4294967294. Traceback: File "D:\python\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 575, in _run_script self._session_state.on_script_will_rerun( File "D:\python\Lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 65, in on_script_will_rerun self._state.on_script_will_rerun(latest_widget_states) File "D:\python\Lib\site-packages\streamlit\runtime\state\session_state.py", line 517, in on_script_will_rerun self._call_callbacks() File "D:\python\Lib\site-packages\streamlit\runtime\state\session_state.py", line 530, in _call_callbacks self._new_widget_state.call_callback(wid) File "D:\python\Lib\site-packages\streamlit\runtime\state\session_state.py", line 274, in call_callback callback(*args, **kwargs) File "E:\pyCharmProject\MoneyPrinterPlus\pages\01_auto_video.py", line 66, in generate_video main_generate_ai_video(video_generator) File "E:\pyCharmProject\MoneyPrinterPlus\main.py", line 266, in main_generate_ai_video main_generate_video_dubbing() File "E:\pyCharmProject\MoneyPrinterPlus\main.py", line 157, in main_generate_video_dubbing extent_audio(audio_output_file, 2) File "E:\pyCharmProject\MoneyPrinterPlus\tools\utils.py", line 138, in extent_audio subprocess.run(command, capture_output=True, check=True) File "D:\python\Lib\subprocess.py", line 571, in run raise CalledProcessError(retcode, process.args,


解决了，把语音识别的key配置好就可以了

**Comment by ddean2009** [comment]
优秀啊 ！

**Comment by scj725** [comment]
为什么有了fasterWhisper这个，还需要配置语音识别服务啊，大佬能解答一下吗
