### ISSUE TITLE
一点AI生产视频就跳这个，方了。

### ISSUE THREAD

**Issue by xin1718734** [ddean2009/MoneyPrinterPlus#21]
FileNotFoundError: Could not find module 'D:\AI\MoneyPrinterPlus-4.2\MoneyPrinterPlus-4.2\venv\Lib\site-packages\azure\cognitiveservices\speech\Microsoft.CognitiveServices.Speech.core.dll' (or one of its dependencies). Try using the full path with constructor syntax.
一点AI生产视频就跳这个，方了。

**Comment by ddean2009** [comment]
你的微软依赖没装好

**Comment by xin1718734** [comment]
> 你的微软依赖没装好

这个已经解决了，现在是生成视频报错：IndexError: list index out of range

**Comment by ddean2009** [comment]
https://aka.ms/vs/17/release/vc_redist.x64.exe   需要安装适用于你的平台的 [Microsoft Visual C++ Redistributable for Visual Studio 2015、2017、2019 和 2022](https://learn.microsoft.com/zh-cn/cpp/windows/latest-supported-vc-redist?view=msvc-170&preserve-view=true)。
