### ISSUE TITLE
python早先装的是3.10， 今天更换成 3.12，报错

### ISSUE THREAD

**Issue by wobohai** [ddean2009/MoneyPrinterPlus#29]
python早先装的是3.10， 今天更换成 3.12，

运行的时候，软件提示  3.10 的路径不存在 python.exe

MoneyPrinterPlus 是在哪里记住了  最早的 3.10 的配置了吗？ 我升级成 python3.12 要怎么修改配置？

**Comment by ddean2009** [comment]
系统PATH里面修改
