### ISSUE TITLE
请问为什么会报这个错误

### ISSUE THREAD

**Issue by wukie-wq** [ddean2009/MoneyPrinterPlus#3]
![image](https://github.com/ddean2009/MoneyPrinterPlus/assets/117264948/cbc814e6-3305-4b10-9525-af90d59e35b4)

**Comment by wukie-wq** [comment]
![image](https://github.com/ddean2009/MoneyPrinterPlus/assets/117264948/f840cff2-23f2-4d80-8cbc-41ef9d57d469)
我选的是moon

**Comment by ddean2009** [comment]
哦哦哦， 更新到最新版本， 这个已经fix了。
