### ISSUE TITLE
Mac版本 视频自动发布 点击环境检测 不报错，但也没有打开页面。

### ISSUE THREAD

**Issue by ZeeMenng** [ddean2009/MoneyPrinterPlus#32]
<img width="1504" alt="image" src="https://github.com/user-attachments/assets/2e29501b-2f0f-497c-9982-a9e489929909">

<img width="1501" alt="image" src="https://github.com/user-attachments/assets/f823ecad-d019-4991-9d7f-af78c5498e6b">

Chrome和ChromeDriver都安装测试正常。

**Comment by ZeeMenng** [comment]
后台日志，也没显示任何错误。
<img width="566" alt="image" src="https://github.com/user-attachments/assets/0c003d50-5ac0-4442-aa8b-a45ddba19043">

**Comment by ddean2009** [comment]
1.  你需要先用调试模式打开chrome。 
2. 然后再点环境测试。

**Comment by ZeeMenng** [comment]
是用调试模式打开的，而且可以确认ChromeDriver和Chrome没有问题，因为我的爬虫程序也用的ChromeDriver，能正常运行的。

Chrome的版本是：128.0.6613.120 (Official Build) (arm64)。
ChromeDriver是： 128.0.6613.18

<img width="1493" alt="image" src="https://github.com/user-attachments/assets/fb4be57c-6657-4297-81c8-b3d89f4d78f9">

**Comment by ddean2009** [comment]
浏览器页面不要开多了， 只开一个试试 。 多了有可能打不开。

**Comment by ZeeMenng** [comment]
好像到不是不能打开多个标签页，但第一次启动Chrome时必须是空白页、第一个打开的标签必须是http://localhost:8501/auto_publish

把所有标签页关掉，然后退出Chrome，再运行命令： chrome --remote-debugging-port=9222，再重新运行项目，可以了发布了。

有点奇怪，不少的细节处不太稳定。

感谢🙏🙏🙏
