### ISSUE TITLE
为什么一直显示请先生成视频资源文件

### ISSUE THREAD

**Issue by aklws** [ddean2009/MoneyPrinterPlus#34]
__syn_core_on_data
core_on_msg:{"header":{"namespace":"SpeechSynthesizer","name":"SynthesisCompleted","status":20000000,"message_id":"931e86ec22cc4725a0b7f84398f43e79","task_id":"db69aabd56d94f7ba92e257bf59b374f","status_text":"Gateway:SUCCESS:Success."}}
__syn_core_on_msg:msg={"header":{"namespace":"SpeechSynthesizer","name":"SynthesisCompleted","status":20000000,"message_id":"931e86ec22cc4725a0b7f84398f43e79","task_id":"db69aabd56d94f7ba92e257bf59b374f","status_text":"Gateway:SUCCESS:Success."}} args=()
__handle_message
__synthesis_completed
__synthesis_completed shutdown done
on_completed:args=>('',) message=>{"header":{"namespace":"SpeechSynthesizer","name":"SynthesisCompleted","status":20000000,"message_id":"931e86ec22cc4725a0b7f84398f43e79","task_id":"db69aabd56d94f7ba92e257bf59b374f","status_text":"Gateway:SUCCESS:Success."}}
core_on_close
ali tts done with result:None
__sr_core_on_close
on_close: args=>('',)
ws exit...
main_generate_video_dubbing end
main_generate_subtitle begin:
selected_audio_provider: Ali
Response status and response reason:
400 Bad Request
Recognize response is:
{'task_id': '2e4b9b971b3c4205b07a01282f46676c', 'result': '', 'status': 40000010, 'message': 'Gateway:FREE_TRIAL_EXPIRED:The free trial has expired!'}
Recognizer failed!
Warning: 'captions' list is empty.
main_get_video_resource begin
resource_provider: pixabay
ffmpeg -i /mnt/d/work/MoneyPrinterPlus/work/1725527290849.wav
音频时长: 25
audio_length: 25
{'totalHits': 0, 'hits': [], 'total': 0}
No videos found.

**Comment by misslou** [comment]
main_get_video_resource begin
resource_provider: pexels
ffmpeg -i /Users/loubin/Desktop/MoneyPrinterPlus/work/1725592409072.wav
音频时长: 24
audio_length: 24
Error: 403
No videos found.



生成视频中...

生成视频配音...

生成视频字幕...

获取视频资源...

视频初始化...

**Comment by ddean2009** [comment]
FREE_TRIAL_EXPIRED:The free trial has expired!'        余额不够了。
