### ISSUE TITLE
在进行AI生成视频的最后一步时，出现Could not locate cudnn_ops_infer64_8.dll. Please make sure it is in your library path!

### ISSUE THREAD

**Issue by Coinsi** [ddean2009/MoneyPrinterPlus#36]
我使用的是，kimi的api配置没有问题，使用的本地的语音模型，语音转文字使用的是本地的fasterwhisper，语音可以合成，到最后生成视频的一步出现

图片如下：
![image-20240906115453220](https://rainhappyblog.oss-cn-beijing.aliyuncs.com/aurora/articlesimage-20240906115453220.png)
到了这个页面后就不会再动了
然后出现：
![image-20240906115704943](https://rainhappyblog.oss-cn-beijing.aliyuncs.com/aurora/articlesimage-20240906115704943.png)
终端的截图如下：
![image-20240906115624150](https://rainhappyblog.oss-cn-beijing.aliyuncs.com/aurora/articlesimage-20240906115624150.png)
我应该怎么解决这个问题

**Comment by ddean2009** [comment]
在网上下载这个dll，放到系统对应的放置dll的目录里面就行了。
