### ISSUE TITLE
No videos found.

### ISSUE THREAD

**Issue by sixll** [ddean2009/MoneyPrinterPlus#37]
请先生成视频资源文件
![73da57900c5e1f19f62d22229ba34e1](https://github.com/user-attachments/assets/9bd54003-6f8d-42fa-95d2-fd5ceec4b2ae)

main_get_video_resource begin
resource_provider: pexels
ffmpeg -i E:\AIjj\MoneyPrinterPlus-main\work\1725595544451.wav
音频时长: 147
audio_length: 147
No videos found.

**Comment by sixll** [comment]
配置的 pexels的key  还是这个问题

**Comment by ddean2009** [comment]
全部截图看看， 少配置了东西吧

**Comment by greytrackk** [comment]
![微信图片_20240919203234](https://github.com/user-attachments/assets/6853a287-17e8-4554-bbc3-58079859bd25)
![微信图片_202409192032341](https://github.com/user-attachments/assets/94f59ba8-5789-4e9d-9334-37b47fcba6d7)
我也是这个报错

**Comment by fanyunli** [comment]
相同的报错，再次检查了pexels的key，没发现问题。

**Comment by ddean2009** [comment]
关键字搜索的视频资源没找到。换个搜索关键字试试。
