### ISSUE TITLE
大家觉得用AI自动生成内容、自动发布、自动运营 公众平台有没有前途？

### ISSUE THREAD

**Issue by ZeeMenng** [ddean2009/MoneyPrinterPlus#38]
ChatTTS  功能太单一，而且只能生成30秒左右的语音，MoneyPrinterPlus调用ChatTTS也就会受这个局限了。

ChatTTS_colab在ChatTTS的基础上做了改进，可以生成长语音，但处理速度慢了很多，不知道为什么。MoneyPrinterPlus也没有支持这种二次开发的开源项目。

GPT-SoVITS 可以用来训练自己想要的音色，MoneyPrinterPlus一样不会支持。

MoneyPrinterPlus在UI设置的视频片段最短为5秒、最长只有30秒，不知道最长片段为什么要加这个局限？

MoneyPrinterPlus 这个想法初听很好，根据一个标题就可以自动生成脚本、视频，但我觉得，这个实际价值可能不会太大。我在[《用AI自动运营公众号可不可行》](https://mp.weixin.qq.com/s?__biz=MzkyMDQzOTgwNw==&mid=2247487110&idx=1&sn=9cb3274c55c37b02794c49530e41d79c&chksm=c1939016f6e41900d6a79168df4f18d2d6d00f8b4ea4f989bd1952e4e1cd8f0acfe952d546e4&token=2110140263&lang=zh_CN#rd)这篇文章中有说明：

`AI生成文章、图片、视频……快捷方便，蹭热点还行，但出不了高质量的、独到的、有价值的内容……想真正吸引粉丝，提升内容本身的含金量才是王道。
`

大家觉得呢？

另外，开源项目，都不太稳定，调试起来各种小问题，最终呈现出的产品的整体效果也到不了理想状态。

**Comment by ddean2009** [comment]
写的很好， 但是不要发广告。
