### ISSUE TITLE
No module named 'aliyunsdkcore'

### ISSUE THREAD

**Issue by jeffreyrobeson** [ddean2009/MoneyPrinterPlus#4]
(base) F:\aigc\MoneyPrinterPlus>pip install aliyunsdkcore
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://pypi.ngc.nvidia.com
Collecting aliyunsdkcore
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/36/80/4fd3153ce15ec7edae283fa937ee1adc0855f980ce248611b2e009d343df/aliyunsdkcore-1.0.3.tar.gz (23 kB)
  Preparing metadata (setup.py) ... done
Collecting pycrypto>=2.6.1 (from aliyunsdkcore)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/60/db/645aa9af249f059cc3a368b118de33889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz (446 kB)
     ---------------------------------------- 446.2/446.2 kB 65.0 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: aliyunsdkcore, pycrypto
  Building wheel for aliyunsdkcore (setup.py) ... done
  Created wheel for aliyunsdkcore: filename=aliyunsdkcore-1.0.3-py2.py3-none-any.whl size=36164 sha256=3d2b9dbeabfd1cb55a8d8500fc6f9ac9a887aded5c50d699e53938ffa9f27298
  Stored in directory: C:\Users\Administrator\AppData\Local\Temp\pip-ephem-wheel-cache-7hlchnnh\wheels\41\b7\32\2aad5acf83a17fd9616ec3f2c0732fd638c45f6c44fe479791
  Building wheel for pycrypto (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
      winrand.c
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(31): error C2061: 语法错误: 标识符“intmax_t”
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(32): error C2061: 语法错误: 标识符“rem”
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(32): error C2059: 语法错误:“;”
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(33): error C2059: 语法错误:“}”
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(35): error C2061: 语法错误: 标识符“imaxdiv_t”
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(35): error C2059: 语法错误:“;”
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(45): error C2143: 语法错误: 缺少“{”(在“__cdecl”的前面)
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(46): error C2146: 语法错误: 缺少“)”(在标识符“_Number”的前面)
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(46): error C2061: 语法错误: 标识符“_Number”
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(46): error C2059: 语法错误:“;”
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(47): error C2059: 语法错误:“)”
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(50): error C2143: 语法错误: 缺少“{”(在“__cdecl”的前面)
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(51): error C2146: 语法错误: 缺少“)”(在标识符“_Numerator”的前面)
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(51): error C2061: 语法错误: 标识符“_Numerator”
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(51): error C2059: 语法错误:“;”
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(51): error C2059: 语法错误:“,”
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(53): error C2059: 语法错误:“)”
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(55): error C2143: 语法错误: 缺少“{”(在“__cdecl”的前面)
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(61): error C2143: 语法错误: 缺少“{”(在“__cdecl”的前面)
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(68): error C2143: 语法错误: 缺少“{”(在“__cdecl”的前面)
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(74): error C2143: 语法错误: 缺少“{”(在“__cdecl”的前面)
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(81): error C2143: 语法错误: 缺少“{”(在“__cdecl”的前面)
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(87): error C2143: 语法错误: 缺少“{”(在“__cdecl”的前面)
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(94): error C2143: 语法错误: 缺少“{”(在“__cdecl”的前面)
      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\inttypes.h(100): error C2143: 语法错误: 缺少“{”(在“__cdecl”的前面)
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycrypto
  Running setup.py clean for pycrypto
Successfully built aliyunsdkcore
Failed to build pycrypto
ERROR: Could not build wheels for pycrypto, which is required to install pyproject.toml-based projects

这个问题如何解决？

**Comment by jeffreyrobeson** [comment]
ModuleNotFoundError: No module named 'aliyunsdkcore'
Traceback:
File "C:\Program Files\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "F:\aigc\MoneyPrinterPlus\pages\01_auto_video.py", line 5, in <module>
    from main import main_generate_video_content, main_generate_ai_video, main_generate_video_dubbing, \
File "F:\aigc\MoneyPrinterPlus\main.py", line 6, in <module>
    from services.audio.alitts_service import AliAudioService
File "F:\aigc\MoneyPrinterPlus\services\audio\alitts_service.py", line 7, in <module>
    from services.alinls.speech_synthesizer import NlsSpeechSynthesizer
File "F:\aigc\MoneyPrinterPlus\services\alinls\speech_synthesizer.py", line 9, in <module>
    from .core import NlsCore
File "F:\aigc\MoneyPrinterPlus\services\alinls\core.py", line 9, in <module>
    from . import logging, token, websocket
File "F:\aigc\MoneyPrinterPlus\services\alinls\token.py", line 3, in <module>
    from aliyunsdkcore.client import AcsClient

**Comment by ddean2009** [comment]
pip install -r requirement.txt  执行了吗？
