### ISSUE TITLE
ImportError: cannot import name 'pairwise' from 'itertools' (unknown location)

### ISSUE THREAD

**Issue by kongmingyang** [ddean2009/MoneyPrinterPlus#45]
配置完之后报如下错误，要如何解决呢

![WeChat6b5fa458ef24c13c89f8b63bb7e95427](https://github.com/user-attachments/assets/bd8017ab-a75e-49e5-a034-54d647b04318)

**Comment by ddean2009** [comment]
python 用3.10 ，或者3.11
