### ISSUE TITLE
到了fasterwhisper这步，报错说 libcudnn_ops_infer.so.8 找不到，整个直接退出了

### ISSUE THREAD

**Issue by sdwcn** [ddean2009/MoneyPrinterPlus#51]
到了fasterwhisper这步，报错说 libcudnn_ops_infer.so.8 找不到，整个直接退出了
```
[out#0/wav @ 0x5636d3316dc0] video:0KiB audio:5246KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.001452%
size=    5246KiB time=00:00:27.97 bitrate=1536.0kbits/s speed= 531x    
Extracted files into /mnt/data/ntg/MoneyPrinterPlus/work/1726944495444.wav
main_generate_video_dubbing end
main_generate_subtitle begin:
selected_audio_provider: fasterwhisper
/mnt/data/ntg/MoneyPrinterPlus/fasterwhisper/tiny True
**Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory**
start.sh: line 14: 10456 Aborted                 (core dumped) streamlit run gui.py
```

然后我在venv下查了，这个文件是在的 ，文件大小也是对的：
/mnt/data/ntg/MoneyPrinterPlus/venv/lib/python3.10/site-packages/nvidia/cudnn/lib/libcudnn_ops_infer.so.8

会是啥问题哈？

**Comment by WeYouHe** [comment]
> 到了fasterwhisper这步，报错说 libcudnn_ops_infer.so.8 找不到，整个直接退出了
> 
> ```
> [out#0/wav @ 0x5636d3316dc0] video:0KiB audio:5246KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.001452%
> size=    5246KiB time=00:00:27.97 bitrate=1536.0kbits/s speed= 531x    
> Extracted files into /mnt/data/ntg/MoneyPrinterPlus/work/1726944495444.wav
> main_generate_video_dubbing end
> main_generate_subtitle begin:
> selected_audio_provider: fasterwhisper
> /mnt/data/ntg/MoneyPrinterPlus/fasterwhisper/tiny True
> **Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory**
> start.sh: line 14: 10456 Aborted                 (core dumped) streamlit run gui.py
> ```
> 
> 然后我在venv下查了，这个文件是在的 ，文件大小也是对的： /mnt/data/ntg/MoneyPrinterPlus/venv/lib/python3.10/site-packages/nvidia/cudnn/lib/libcudnn_ops_infer.so.8
> 
> 会是啥问题哈？

这个问题怎么解决的啊？我也遇到了，可以帮下忙吗？
