### ISSUE TITLE
请先生成视频资源文件

### ISSUE THREAD

**Issue by wuhanfanyi** [ddean2009/MoneyPrinterPlus#54]
main_get_video_resource begin
resource_provider: pexels
ffmpeg -i D:\soft\MoneyPrinterPlus-main\work\1727009140354.wav
音频时长: 56
audio_length: 56
Error: 403
No videos found.

用了各种各样的关键词还是不行。

**Comment by mu0641** [comment]
Error: 403
No videos found.   我也是一样

**Comment by ddean2009** [comment]
v4.6版本已修复。
