### ISSUE TITLE
生成视频报错，有没有大佬指点一下

### ISSUE THREAD

**Issue by authorz** [ddean2009/MoneyPrinterPlus#59]
报错：
`CalledProcessError: Command '['ffmpeg', '-i', 'F:\\MoneyPrinterPlus-windows\\work\\1727256042420.wav', '-af', 'apad=pad_dur=2', 'F:\\MoneyPrinterPlus-windows\\work\\1727256042420.temp.wav']' returned non-zero exit status 3199971767.`
系统环境(win11专业版, 22H2)：
![image](https://github.com/user-attachments/assets/19bf6f26-bde1-43b7-8189-e186a0d0e4a7)
ffmpeg（v7.0.2）:
![image](https://github.com/user-attachments/assets/b33eb377-38d4-44cc-9b54-388a61418e7f)
配置：
![image](https://github.com/user-attachments/assets/9ecf9d0a-0ae9-4aa1-aac8-c256a0ef8526)
阿里云项目配置：
录音文件识别（极速版）：已开通商用
语音合成：已开通商用
work文件夹里面的wav文件均为0字节

**Comment by EQEeeeee** [comment]
同

**Comment by EQEeeeee** [comment]
有没有大佬解决一下

**Comment by city10666** [comment]
我之前好像也出现过，ffmpeg版本好不对，删掉重新搞，版本好显示数字的就正常了

**Comment by fenghaoyu16** [comment]
我也要这个问题，重新安装ffmpeg也不行
