### ISSUE TITLE
按照教程安装完毕后，语音用的是腾讯云的KEY。语音可以试听也扣了点数，但运行出现附件的错误，求帮助

### ISSUE THREAD

**Issue by tanianarsha** [ddean2009/MoneyPrinterPlus#72]
按照教程安装完毕后，语音用的是腾讯云的KEY。输入appID这些后，语音可以试听也扣了点数，但运行出现附件的错误，求帮助

![微信图片_20241024192435](https://github.com/user-attachments/assets/a1569582-83cd-49b4-b645-c1431807c681)

**Comment by ddean2009** [comment]
python没装好吧

**Comment by tanianarsha** [comment]
FFMPEG的问题，弄好了不过微软云又出错了
