### ISSUE TITLE
两个项目怎么都差不多

### ISSUE THREAD

**Issue by code-innovator-zyx** [ddean2009/MoneyPrinterPlus#8]
和  https://github.com/harry0703/MoneyPrinterTurbo  这个项目咋这么像

**Comment by ddean2009** [comment]
功能不一样， 这个功能强大太多了。  支持国产语音服务。 支持转场动画。支持特效。 支持批量视频混剪。

**Comment by ddean2009** [comment]
谁用谁知道。

**Comment by code-innovator-zyx** [comment]
> 谁用谁知道。

效果应该都是一样的，视频和文案牛头不对马嘴

**Comment by ddean2009** [comment]
看看我的： 批量视频混剪功能，必须对应上。
